---
  # tasks file for ansible-gitlab-ce
  - include: debian.yml
    when: ansible_os_family == "Debian"

  - include: redhat.yml
    when: ansible_os_family == "Redhat"

  - include: install.yml

  - include: config_gitlab.yml
  tags:
    - config_gitlab
  when: config_gitlab