---
  - name: update the packages
    apt: 
      update_cache: yes 
      force_apt_get: yes 
      cache_valid_time: 3600

  - name: Install the JDK8
    apt:
      name: openjdk-8-jdk
      state: present
  
  - name: Install the Ansible
    apt:
      name: ansible
      state: present
  
  - name: Install the python3
    apt:
      name: python3
      state: present
    
  - name: Install the pip3
    apt:
      name: python3-pip
      state: present
  
  - name: Install the php
    apt:
      name: php
      state: present