# download nexus package 
  - name: download the nexus packages
    unarchive:
      src: "{{ nexus_url }}"
      dest: "{{ nexus_dir }}"
      remote_src: yes
      extra_opts: [--strip-components=1]
  
  - name: uncomment the run as user fron nexus file
    lineinfile:
      path: "{{ nexus_rc_file }}"
      regexp: 'run_as_user="nexus"'
      line: run_as_user="nexus"
  
  - name: change the ownership of file
    file:
      path: "{{ nexus_dir }}"
      owner: "{{ nexus_user }}"
      group: "{{ nexus_group }}"
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory
  
  - name: change the ownership of file
    file:
      path: "{{ sonar_type_dir }}"
      owner: "{{ nexus_user }}"
      group: "{{ nexus_group }}"
      mode: "u+rwx,g+rx,o=rx"
      recurse: yes
      state: directory
    
  - name: create symbolic links to /etc/init.d/nexus
    file: 
      src: "{{ nexus_service_loc }}"
      dest: /etc/init.d/nexus 
      state: link
      force: yes
    
    
  - name: configure runlevel links for nexus
    command: update-rc.d nexus defaults
    notify: 
      - start nexus service